=== samirmenon/rpl/schema/rasm/rasm.schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "rpl::rasm",
  "description" : "This is the schema for a basic rpl robot assembly command",
  "type" : "object",
  "properties" : {
    "command" : { "type" : "string" },
    "params"  : { "type" : "object" },
    "type"    : { "type" : "string" },
    "meta"    : {
      "description" : "A short text description of the rpl robot assembly command",
      "type" : "string"
    }
  },
  "required" : ["command", "type", "params"]
}

=== samirmenon/rpl/schema/rasm/tsinmulti.json
{
  "command" : "tsinmulti",
  "type" : "rasm",
  "params" : {
    "axis" : [[1, 0, 0], [0, 1, 0]],
    "ampl" : [1, 0.3],
    "freq" : [1.2, 2,1],
    "n-waves" : [1, 0.5],
    "frame" : {
      "rb" : "link4",
      "R" : [1, 0, 0, 0, 1, 0, 0, 0, 1],
      "p" : [0, 0, 0]
    }
  },
  "meta" : "Sine-wave motion rasm command; along one or more axes of a specific frame."
}

=== samirmenon/rpl/schema/rasm/fx3.json
[
  {
    "command" : "fx3",
    "type" : "rasm",
    "params" : {
      "f" : [1, 0, 0],
      "t" : 1.2,
      "frame" : {
        "rb" : "link4",
        "R" : [1, 0, 0, 0, 1, 0, 0, 0, 1],
        "p" : [0, 0, 0]
      }
    },
    "meta" : "Force-3d rasm command; xyz (3d) forces at a frame transform wrt. rigid body's frame."
  },
  {
    "command" : "fx3",
    "type" : "rasm",
    "params" : {
      "f" : [1, 0, 0],
      "t" : 3.2,
      "frame" : {
        "rb" : "link4",
        "ori-rb" : "ground",
        "p" : [0, 0, 0]
      }
    },
    "meta" : "Applies forces in the ground frame."
  },
  {
    "command" : "fx3",
    "type" : "rasm",
    "params" : {
      "f" : [1, 0.1, 0],
      "t" : 3.2,
      "s" : [0, 1, 1],
      "frame" : { "rb" : "link4"  }
    },
    "meta" : "Applies forces in the link's frame with a selection vector `s`. i.e., only y-axis for this object"
  }
]

=== samirmenon/rpl/schema/rasm/fx6.json
{
  "command" : "fx6",
  "type" : "rasm",
  "params" : {
    "f" : [1, 0, 0, 0.2, 0.1, 0.3],
    "t" : 1.2,
    "frame" : {
      "rb" : "link4",
      "R" : [1, 0, 0, 0, 1, 0, 0, 0, 1],
      "p" : [0, 0, 0]
    }
  },
  "meta" : "An exemplar object for the <force 6d> rpl assembly command. Supports 6-axis forces."
}
